#   A basic travis.yml boilerplate for Django projects
#
#   The set-up assumes a postgreSQL database.
#
#   Replace the following variables in the code:
# * your_project_settings
# * Streamweaver
# * https://github.com/APTrust/APTrustDPN

language: python

python:
  - 3.4

services: postgresql

env:
  - DJANGO=1.5

branches:
  only:
    - master
    - develop

before_install:
  - cp dpnode/localsettings_dist.py dpnode/localsettings.py
  - export DJANGO_SETTINGS_MODULE=dpnode.settings
  - export PYTHONPATH=$HOME/builds/APTrust/APTrustDPN
  - export PIP_USE_MIRRORS=true

install:
  - pip install -r requirements.txt
  - pip install -r requirements_dev.txt
  - pip install django==$DJANGO --quiet
  - pip install psycopg2 --quiet

before_script:
  - psql -c "CREATE DATABASE travisdb;" -U postgres

script:
  - python manage.py syncdb --noinput

notifications:
  email:
    recipients:
      - "scott.turnbull@aptrust.org"
    on_success: "change"
    on_failure: "always"